### ISSUE TITLE
How to train or test this code?

### ISSUE THREAD

**Issue by MahmoudSaleh93** [PurdueDigitalTwin/ViT-DD#1]
Excellent work. Please I need to retrain the model, but there are many errors. please give me the command that I use to run **train.py**
Thanks in advance

**Comment by maysonma** [comment]
Hi, thanks for your interest. Please try 
`python3 train.py fit --config configs/vitdd_aucdd.yaml`

**Comment by maysonma** [comment]
BTW, if you would like to test the model with our pretrained weights. Please first change the 'ckpt_path:' to the correct path to the ckpt file in the config file to use and then run
`python3 train.py test --config configs/xxx.yaml`

**Comment by Abhilashsabhi** [comment]
How do you do real-time inference with your pretrained weights?
