### ISSUE TITLE
a question about the validation set and the test set

### ISSUE THREAD

**Issue by knimet** [PurdueDigitalTwin/ViT-DD#4]
hi, I noticed that the validation set and test set you used are the same. Do the results reported in the paper also follow this configuration?

**Comment by maysonma** [comment]
Hello! Thank you for bringing up this issue. Yes, you are correct that the validation set and test set used in our work are the same, following the configuration of previous studies to ensure fair comparison. It's worth noting that the SFDDD dataset does not provide labels for the test set, which makes it difficult to use a separate test set for evaluation. However, we took care to ensure that the reported results are reliable and accurate based on the established practices in the field.
